#!/usr/bin/env bash
# Установщик GUI-части NTFS-утилиты:
#  1. собирает Swift menu-bar приложение → ~/Applications/NTFSMounter.app
#  2. ставит LaunchDaemon (root) для авто-перемонтирования
#  3. ставит LaunchAgent (user) для авто-запуска menu-bar app при логине
#  4. (опционально) добавляет sudoers-правило, чтобы remount не спрашивал пароль
#
# Запуск:  bash ~/ntfs-utility/install-gui.sh

set -euo pipefail

C_GREEN='\033[0;32m'
C_YELLOW='\033[1;33m'
C_RED='\033[0;31m'
C_BLUE='\033[0;34m'
C_OFF='\033[0m'
log()  { printf "${C_BLUE}==>${C_OFF} %s\n" "$*"; }
ok()   { printf "${C_GREEN}✓${C_OFF}  %s\n" "$*"; }
warn() { printf "${C_YELLOW}!${C_OFF}  %s\n" "$*"; }
die()  { printf "${C_RED}✗ %s${C_OFF}\n" "$*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "Только для macOS."

# Должен быть установлен ntfs-mount из основного install.sh
if [[ ! -x /usr/local/bin/ntfs-mount ]]; then
  die "Сначала запустите основной установщик: bash ~/ntfs-utility/install.sh"
fi

UTIL_DIR="$HOME/ntfs-utility"
APP_DIR="$HOME/Applications/NTFSMounter.app"
APP_BIN="$APP_DIR/Contents/MacOS/NTFSMounter"
APP_PLIST="$APP_DIR/Contents/Info.plist"

# 1. Проверим swiftc
if ! command -v swiftc >/dev/null 2>&1; then
  warn "swiftc не найден. Установите Command Line Tools:"
  warn "    xcode-select --install"
  die "После установки CLT повторите этот скрипт."
fi
ok "swiftc найден: $(swiftc --version | head -1)"

# 2. Собираем .app bundle
log "Собираю NTFSMounter.app в $APP_DIR..."
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

swiftc -O -o "$APP_BIN" "$UTIL_DIR/NTFSMounter.swift" \
  -framework Cocoa

cat > "$APP_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>NTFS Mounter</string>
    <key>CFBundleDisplayName</key><string>NTFS Mounter</string>
    <key>CFBundleIdentifier</key><string>com.user.ntfsmounter</string>
    <key>CFBundleExecutable</key><string>NTFSMounter</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSUIElement</key><true/>
    <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
EOF
ok "Приложение собрано: $APP_DIR"

# 3. LaunchDaemon (root) — автомонтирование
log "Устанавливаю automount-daemon (root)..."
sudo mkdir -p /usr/local/libexec
sudo install -m 0755 "$UTIL_DIR/automount-daemon.sh" /usr/local/libexec/ntfs-automount-daemon.sh

DAEMON_PLIST="/Library/LaunchDaemons/com.user.ntfs-automount.plist"
DAEMON_PLIST_TMP="$(mktemp)"
sed "s|__OWNER_USER__|$(id -un)|g" "$UTIL_DIR/com.user.ntfs-automount.plist" > "$DAEMON_PLIST_TMP"

# Останавливаем старую версию, если есть
if sudo launchctl print system/com.user.ntfs-automount >/dev/null 2>&1; then
  sudo launchctl bootout system "$DAEMON_PLIST" 2>/dev/null || true
fi

sudo install -m 0644 -o root -g wheel "$DAEMON_PLIST_TMP" "$DAEMON_PLIST"
rm -f "$DAEMON_PLIST_TMP"
sudo touch /var/log/ntfs-automount.log
sudo chmod 0644 /var/log/ntfs-automount.log

sudo launchctl bootstrap system "$DAEMON_PLIST"
sudo launchctl enable system/com.user.ntfs-automount
ok "Демон активен. Лог: /var/log/ntfs-automount.log"

# 4. LaunchAgent (user) — авто-запуск menu-bar app
log "Устанавливаю LaunchAgent (menu-bar app при логине)..."
mkdir -p "$HOME/Library/LaunchAgents" "$HOME/Library/Logs"
AGENT_PLIST="$HOME/Library/LaunchAgents/com.user.ntfsmounter.plist"
sed -e "s|__APP_PATH__|$APP_DIR|g" -e "s|__HOME__|$HOME|g" \
  "$UTIL_DIR/com.user.ntfsmounter.plist" > "$AGENT_PLIST"

# Перезапускаем агент
launchctl bootout "gui/$(id -u)/com.user.ntfsmounter" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$AGENT_PLIST"
launchctl enable "gui/$(id -u)/com.user.ntfsmounter"
ok "Menu-bar приложение запущено. Иконка появится в правом верхнем углу."

# 5. (Опционально) sudoers — чтобы ручной remount из меню не спрашивал пароль
SUDOERS_FILE="/private/etc/sudoers.d/ntfs-mounter"
read -r -p "Разрешить ntfs-mount запускаться без пароля для пользователя $(id -un)? [y/N] " yn
if [[ "$yn" =~ ^[Yy]$ ]]; then
  TMP_SUDO="$(mktemp)"
  cat > "$TMP_SUDO" <<EOF
# Generated by ntfs-utility/install-gui.sh
$(id -un) ALL=(root) NOPASSWD: /usr/local/bin/ntfs-mount, /usr/local/bin/ntfs-3g, /usr/local/sbin/mount.ntfs-3g
EOF
  sudo visudo -c -f "$TMP_SUDO" >/dev/null \
    && sudo install -m 0440 -o root -g wheel "$TMP_SUDO" "$SUDOERS_FILE" \
    && ok "Sudoers правило установлено: $SUDOERS_FILE" \
    || warn "Sudoers правило не прошло проверку — пропускаю"
  rm -f "$TMP_SUDO"
else
  warn "Пропустили sudoers. При ручном remount из меню будет всплывать запрос пароля macOS."
fi

echo
ok "Готово! Иконка диска должна появиться в menu bar."
cat <<'EOF'

Полезные команды
────────────────
Перезапустить демон автомонтирования:
    sudo launchctl kickstart -k system/com.user.ntfs-automount

Перезапустить menu-bar приложение:
    launchctl kickstart -k "gui/$(id -u)/com.user.ntfsmounter"

Посмотреть лог автомонтирования:
    tail -f /var/log/ntfs-automount.log

Удалить всё:
    bash ~/ntfs-utility/uninstall-gui.sh
EOF
